"""Move tracking unit to key

Revision ID: 36b7c813de76
Revises: 0003_add_key_frequency
Create Date: 2026-08-12 01:03:49.896505

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36b7c813de76"
down_revision: str | None = "0003_add_key_frequency"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("tracking_unit_fkey"), "tracking", type_="foreignkey")
    op.drop_column("tracking", "unit")
    op.add_column(
        "tracking_key",
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.create_foreign_key(None, "tracking_key", "tracking_unit", ["unit"], ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tracking_key", type_="foreignkey")
    op.drop_column("tracking_key", "unit")
    op.add_column(
        "tracking", sa.Column("unit", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key(
        op.f("tracking_unit_fkey"), "tracking", "tracking_unit", ["unit"], ["name"]
    )
    # ### end Alembic commands ###
